language: r
pandoc_version: 2.7
install: true
script: make
before_deploy: "export RELEASE_NAME=`date +%Y%m%d`-$TRAVIS_BUILD_NUMBER"
deploy:
  skip-cleanup: true
  provider: releases
  api_key:
    secure: SdGs9KD+GGrPZbHcLVmeJDNXdhPt2qDQEAduy8Fd1+tlNgDyqn6PDHbqDwXEgEh0lgGnyaYF4Ajp/31X28T9kdgYPjRoS2bZMr4s9W9jVT/ZXOBXBXG4H6UK+I8om858Bk6xdZADn/RdklNLq6ItErFeXQ0WgeY6/HtIccwsSERqON7WH5siX0YAOHTEsLSZsoEsLglgg7Ap6zPugGrBC2MqMV8KXaZTJJEQ034HI8yLC6bKjpI2lK6BwTiH6f/2ZmWIf+FKEIkYjOlsz49i6N9xQm6lfCvVHF25kwZg4eRQmoTf4TC0MXXnkjS+dM/ren0fbCbWHZ9yYFBvAHptE47Bqyl1drVruBKmT4OsQBE4HMqTzmfsa/rZ8RoVpVukvz0DfooFrNRPtI2wRUgxeaQA2lQEdWQV4ttVF8McsPGifUenZsWUQJKt05IFlbkW6dALPWIrklsgj3p4t6vAjw2HyxPFuhaVAmINorxGAXtPMxVk34E2wdjTT/gRFf/AoTySRdtnr8iMDexINgEHw62lmBVIRolrmIYeJ57IECKA7z7OCGjqbIYlad6pjrYV0kbrIoxP0XY/YPIiskGNrjnxFbmKqtMHkmoKwOwtD7+a7pfl/Thj2p80HoMzEwELuUUh625kM0woMLHD3uUub05hzxgR4oF7lkTTt5XbDOY=
  file: 
    - constitution.pdf
    - constitution.docx
  on:
    repo: ysu-game-devs/governing-documents
    all_branches: true
  name: $RELEASE_NAME
